### ISSUE TITLE
Failed to activate the tree-view-panes package

### ISSUE THREAD

**Issue by chinelo-okoli** [susisu/tree-view-panes#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.0.1
**Thrown From**: [tree-view-panes](https://github.com/susisu/tree-view-panes) package 0.3.7

### Stack Trace

Failed to activate the tree-view-panes package

```
At Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.

Error: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at Injector.injectView (/packages/tree-view-panes/lib/injector.js:102:26)
    at Injector.setTreeViewItem (/packages/tree-view-panes/lib/injector.js:80:14)
    at /packages/tree-view-panes/lib/injector.js:29:14)
    at TreeViewPanes.activate (/packages/tree-view-panes/lib/tree-view-panes.js:19:21)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3569498)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3568910
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3566488)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3568770
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3568713)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383522)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:916621
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:911227)
    at s (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1134638)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1134726
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1133394)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-formatter-jsbeautify 1.1.2 
autocomplete-xml 0.11.0 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.0.0 
linter-ui-default 2.1.5 
linter-xmllint 1.4.4 
tag 0.5.0 
tree-view-panes 0.3.7 
xml-decoder 1.1.0 
xml-formatter 0.13.0 
```

**Comment by toridoriv** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [tree-view-panes](https://github.com/susisu/tree-view-panes) package 0.3.7


### Stack Trace

Failed to activate the tree-view-panes package

```
At Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.

Error: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at Injector.injectView (/packages/tree-view-panes/lib/injector.js:102:26)
    at Injector.setTreeViewItem (/packages/tree-view-panes/lib/injector.js:80:14)
    at /packages/tree-view-panes/lib/injector.js:29:14)
    at TreeViewPanes.activate (/packages/tree-view-panes/lib/tree-view-panes.js:19:21)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3569498)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3568910
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3566488)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3568770
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3568713)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383522)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:916621
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:911227)
    at s (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1134638)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1134792
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1133394)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
     -2:21.4.0 settings-view:open (textarea.)
     -1:24.6.0 core:confirm (input.hidden-input)
     -1:05.2.0 core:select-all (input.hidden-input)
     -1:03.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
atom-typescript 14.1.2 
busy-signal 2.0.1 
Chromo-Color-Previews 1.8.3 
city-lights-icons 1.1.1 
color-indent 1.1.0 
comment-that 1.1.0 
docblockr 0.13.7 
dracula-syntax 3.0.2 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
expand-region 0.5.0 
file-icons 2.1.44 
git-control 0.9.0 
git-plus 8.7.1 
git-time-machine 2.1.0 
hex-to-rgba 2.0.0 
highlight-line 0.12.0 
highlight-selected 0.17.0 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.19.0 
linter 3.1.1 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-ui-default 2.1.5 
local-history 4.3.1 
markdown-preview-plus 4.8.4 
merge-conflicts 1.4.5 
nebula-ui 0.9.3 
open-dir-in-iterm 0.2.0 
pigments 0.40.6 
prettier-atom 0.60.1 
project-plus 1.0.0 
react 0.18.0 
split-diff 1.6.1 
todo-show 2.3.2 
tree-view-panes 0.3.7 
xatom-debug 1.6.11 
xatom-debug-chrome 0.7.4 
xatom-debug-nodejs 0.9.3 
```
