### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by chrisdrackett** [susisu/tree-view-panes#3]
[Enter steps to reproduce:]

1. Open or close a file from the tree view

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [tree-view-panes](https://github.com/susisu/tree-view-panes) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/cwd/Dropbox/Settings/atom/packages/tree-view-panes/lib/pane-controller.js:220

TypeError: Cannot read property 'item' of undefined
    at PaneController.removeItemControllerOf (/packages/tree-view-panes/lib/pane-controller.js:220:19)
    at /packages/tree-view-panes/lib/pane-controller.js:46:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:613:1)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:685:1)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:339:1)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:227:1)
```

### Commands

```
     -1:40 window:toggle-dev-tools (atom-pane.pane)
     -0:03.8.0 core:close (div.tool-panel.tree-view)
```

### Non-Core Packages

```
apex-syntax 0.1.0 
apex-ui 0.2.1 
apex-ui-slim 0.0.0 
atom-material-syntax 1.0.6 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.3 
atom-ternjs 0.18.3 
autocomplete-emojis 2.5.0 
autocomplete-json 5.5.0 
bamboo-ui 0.0.1 
base16-syntax 1.8.0 
busy-signal 1.4.1 
color-picker 2.2.5 
docblockr 0.9.4 
duotone-light-syntax 2.1.0 
file-icons 2.1.6 
flex-tool-bar 0.12.0 
git-line 0.6.0 
highlight-selected 0.13.1 
html-entities 0.4.0 
intentions 1.1.2 
jsformat 0.9.3 
language-babel 2.61.0 
linter 2.1.4 
linter-eslint 8.1.7 
linter-jsonlint 1.3.0 
linter-ui-default 1.5.4 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
multi-cursor 2.1.5 
native-ui 0.20.6 
northem-light-atom-ui 2.1.0 
open-this 0.4.0 
opened-files 0.3.6 
package-cop 0.2.10 
pane-split-moves-tab 0.1.0 
pigments 0.39.1 
prettier-atom 0.31.1 
pretty-json 1.6.3 
proton-light 0.2.0 
set-syntax 0.3.2 
seti-syntax 1.1.3 
seti-ui 1.8.0 
shiny-ui 0.36.0 
slack-ui 0.8.0 
sort-lines 0.14.0 
tool-bar 1.1.0 
tree-view-panes 0.3.1 
zentabs 0.8.8 
```

**Comment by susisu** [comment]
Thank you for reporting!

I couldn't reproduce it (perhaps this is caused by one of those packages?), but I added boundary checks to suppress this kind of errors.
Please try out v0.3.2.

If you still have some errors or unexpected behaviors, please let me know again.

**Comment by chrisdrackett** [comment]
yeah, not sure, this seems to have fixed the issue though, thanks!
