### ISSUE TITLE
Uncaught Error: item index does not match

### ISSUE THREAD

**Issue by github-sjacobs** [susisu/tree-view-panes#5]
[Enter steps to reproduce:]

Not really sure. I noticed that the minimap was not displayed for one of my tabs for some reason. I closed that tab and saw this error.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: "CentOS Linux
**Thrown From**: [tree-view-panes](https://github.com/susisu/tree-view-panes) package 0.3.5

### Stack Trace

Uncaught Error: item index does not match

```
At /export/home/sjacobs/.atom/packages/tree-view-panes/lib/pane-controller.js:224

Error: item index does not match
    at PaneController.removeItemControllerOf (/packages/tree-view-panes/lib/pane-controller.js:224:13)
    at /packages/tree-view-panes/lib/pane-controller.js:46:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:613:26)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:685:22)
    at TabBarView.module.exports.TabBarView.closeTab (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
     -4:29.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -4:20.2.0 core:confirm (input.hidden-input)
     -3:48.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -3:43.2.0 core:confirm (input.hidden-input)
  2x -0:54.5.0 symbols-tree-view-fix:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.30.1 
code-dark-ui 0.7.0 
counter 0.3.5 
file-icons 2.1.7 
geiger 2.1.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
language-lua 0.9.11 
line-count-status 0.0.3 
line-ending-converter 1.3.2 
markdown-preview-plus 2.4.9 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
sort-lines 0.14.0 
space-tab 0.4.2 
symbols-tree-view 0.14.0 
symbols-tree-view-fix 0.13.3 
sync-settings 0.8.2 
tree-view-autoresize 2.1.0 
tree-view-panes 0.3.5 
tree-view-sort 0.7.0 
tron-legacy-syntax 0.5.0 
tron-legacy-ui 0.6.0 
Visual-Studio-2015-Dark-Theme 2.4.2 
```

**Comment by susisu** [comment]
I knew it can happen when something goes wrong (related to #3), and actually happened... 😿

I will fix it. Thanks for reporting!

**Comment by susisu** [comment]
I added procedures to restore from a broken state in 5bb4f0a.
Maybe reporting errors is better, though.

I guess something is going wrong out of this package (because I have never got this error), so it is just an ad-hoc solution rather than the radical solution.
