### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by github-sjacobs** [susisu/tree-view-panes#6]
[Enter steps to reproduce:]
Not sure. I had around 10 files open. I opened another and it was not added to the Open Files list. I began closing files using the 'x' on the Open Files list and got this error.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: "CentOS Linux
**Thrown From**: [tree-view-panes](https://github.com/susisu/tree-view-panes) package 0.3.5

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /usr/share/atom/resources/app/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/usr/share/atom/resources/app/src/item-registry.js:11:21)
    at PaneContainer.didAddPaneItem (/usr/share/atom/resources/app/src/pane-container.js:265:29)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:532:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:468:20)
    at PaneController.activateItem (/packages/tree-view-panes/lib/pane-controller.js:186:15)
    at HTMLLIElement.ItemController.onClick (/packages/tree-view-panes/lib/item-controller.js:163:19)
```

### Commands

```
  2x -8:06.3.0 core:move-down (input.hidden-input)
     -7:51.9.0 autocomplete-plus:confirm (input.hidden-input)
  3x -7:46.7.0 core:backspace (input.hidden-input)
     -7:28.1.0 core:copy (input.hidden-input)
     -7:22.9.0 core:paste (input.hidden-input)
 14x -7:16.3.0 core:move-right (input.hidden-input)
  2x -7:13 editor:newline (input.hidden-input)
     -7:06.6.0 core:save (input.hidden-input)
     -2:39.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  2x -2:37.8.0 core:backspace (input.hidden-input)
     -2:31.9.0 core:confirm (input.hidden-input)
     -2:09.1.0 core:backspace (input.hidden-input)
     -1:36.2.0 core:undo (input.hidden-input)
     -1:22.3.0 core:delete (input.hidden-input)
     -1:04.7.0 core:save (input.hidden-input)
     -0:54.6.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.1 
code-dark-ui 0.7.0 
counter 0.3.5 
file-icons 2.1.7 
geiger 2.1.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
language-lua 0.9.11 
line-count-status 0.0.3 
line-ending-converter 1.3.2 
markdown-preview-plus 2.4.9 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
sort-lines 0.14.0 
space-tab 0.4.2 
symbols-tree-view 0.14.0 
symbols-tree-view-fix 0.13.3 
sync-settings 0.8.2 
tree-view-autoresize 2.1.0 
tree-view-panes 0.3.5 
tree-view-sort 0.7.0 
tron-legacy-syntax 0.5.0 
tron-legacy-ui 0.6.0 
Visual-Studio-2015-Dark-Theme 2.4.2 
```

**Comment by susisu** [comment]
Thank you for reporting, but I can do nothing about it.

This kind of errors are sometimes raised when dealing with non-file items, like "About" or "Settings" (see, for example, atom/tabs#234 and atom/settings-view#723), and the one you reported seems to be the same case.
